### ISSUE TITLE
Request A Release

### ISSUE THREAD

**Issue by Coekjan** [mozilla/cbindgen#1025]
My project is blocked by #1013 these days. Although it is fixed on the main branch, cbindgen has not released a new version yet. I know I can use `cbindgen = { git = ..., rev = ... }` in my Cargo.toml to specify the unreleased version, **which however is a stopgap measure** in my view.

I see the readme says:

https://github.com/mozilla/cbindgen/blob/89a9faa97cc267e90fc95a1cc6177a001aed5b51/README.md#L94-L98

So, kindly ping @emilio :)

**Comment by youknowone** [comment]
Rather than directly depending on a git version, adding a patch revision is also possible until a new cargo release

```toml
[patch.crates-io]
cbindgen = { git = "https://github.com/mozilla/cbindgen.git", rev = "..." }
```
