### ISSUE TITLE
`rename_types` does not appear to work

### ISSUE THREAD

**Issue by fw-immunant** [mozilla/cbindgen#877]
This may well be an issue of my understanding, but I've read the documentation and would expect this to result in a `memory_map` struct rather than `MemoryMap`:

`cbindgen.toml`:
```toml
language = "C"

[export]
item_types = ["structs", "opaque", "functions"]

[export.mangle]
rename_types = "snake_case"
```

`lib.rs`:
```rust
#[repr(C)]
pub struct MemoryMap {
    x: u32,
}

#[no_mangle]
pub extern "C" fn memory_map_new() -> Box<MemoryMap> {
    Box::new(MemoryMap {})
}
```

`Cargo.toml`:
```toml
[package]
name = "cbindgen-test"
version = "0.1.0"
edition = "2021"
```

Output:
```C
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct MemoryMap {
  uint32_t x;
} MemoryMap;

struct MemoryMap *memory_map_new(void);
```

Am I misunderstanding which types `rename_types` is supposed to apply to? I know this can be worked around with the `export.rename` feature, but this seems to be what `rename_types` should do in general, rather than having to write out each renaming one by one.
